### ISSUE TITLE
Doesn't work with Lingua

### ISSUE THREAD

**Issue by clutchmarketing** [modmore/MagicPreview#12]
When the multi-lingual plugin Lingua is installed, Magic Preview doesn't provide a preview of the template variables in any of the languages.

**Comment by muzzwood** [comment]
Hi @clutchmarketing 
The next release of MagicPreview will include the event `OnResourceMagicPreview` which will allow other extras to hook in to the preview action and parse the output needed. 

To make Lingua compatible, the maintainer/contributor can use a plugin like this:
```
<?php

switch ($modx->event->name) {
    case 'OnResourceMagicPreview':
   
    /** @var modResource $resource */
    $resource->setContent() etc.
    // Parse resource here to include all values before displaying preview

    break;
}

```
