### ISSUE TITLE
Can't display Ressource after Preview has been generated

### ISSUE THREAD

**Issue by darQrrR** [modmore/MagicPreview#13]
Expected behavior:
- Click Preview
- Preview shows up
- Click Show 
- Ressource shows up

Actual behavior:
- Click Preview
- Preview shows up
- Click Show 
- Blank page

**Comment by muzzwood** [comment]
Fixed in https://github.com/modmore/MagicPreview/commit/f8bc482eaef27bc3e8b562a33b728ef3f8e05c6c
