### ISSUE TITLE
Link to resource in Preview window is confusing

### ISSUE THREAD

**Issue by SnowCreative** [modmore/MagicPreview#18]
After clicking the Preview button, a new window opens with the preview, plus a header with browser widths on the right, and a link on the left that says "Preview for" plus the resource name, which is linked to the Manager URL for that resource. If you click this link, though, a new editing window opens. The window loads the saved version of the page, so it DOES NOT include the edits you're working on. If people click this link and edit, they will lose the edits they were previewing. 

Since the Preview window only opens after clicking the Preview button while editing, a better option would be to either link the resource name to a javascript to close the window, or else just have a single link that says "Close Preview" to close the window to go back to the live editing page in MODX.

**Comment by Mark-H** [comment]
That's a good point. Alternatively perhaps we can make it link to the resource panel which then loads the data from the preview... but that may open up another can of compatibility worms...

**Comment by sscWhitevision** [comment]
The preview window will open in a new window. In my opinion a "close preview button" would be better than the link back to the backend in the moment.

**Comment by SnowCreative** [comment]
> but that may open up another can of compatibility worms...

Yes, that would create a second window with the resource open for editing, which would be confusing even if the same data is initially loaded.

**Comment by muzzwood** [comment]
We've added a button which closes the preview tab/window.
Perhaps in the future we could link to the resource loading the preview data as Mark suggested, though I think that will require a hefty amount of work.
