### ISSUE TITLE
Preview Page not loading on MODX 3.0.1

### ISSUE THREAD

**Issue by patrickatwsrn** [modmore/MagicPreview#25]
Loading animation goes on forever.

<img width="972" alt="image" src="https://user-images.githubusercontent.com/68318893/168395873-0f763050-760d-4d1a-9adc-86c5821a7944.png">

I can't find any errors in my server logs (apache, modsecurity, etc.) or inside the modx manager log.

Browser console is also not giving any feedback.

---

magicpreview-1.2.1-pl
MODX 3.0.1
Apache/Plesk

**Comment by patrickatwsrn** [comment]
Update: Problem happens on php 7.4.29, 8.0.18 and 8.1.5.

**Comment by patrickatwsrn** [comment]
Its also happending on current versions of Firefox and Chrome.

**Comment by patrickatwsrn** [comment]
I can also rule out published status and maintenance mode.

As administrator/sudo user I also dare to rule out a permission issue.

**Comment by muzzwood** [comment]
Hey @patrickatwsrn 
- Could you try wiping both your MODX cache, and your browser cache and see if that helps?
- Is this happening on a standard resource, or something else like a ContentBlocks or Collections resource?
- In your browser console, could you check what content the response contains?

**Comment by Mark-H** [comment]
Closing as there hasn't been feedback. 

If you're still having these issues, please reopen. It's worth checking the hash in the browser url for the preview that keeps looping - does it get a unique hash after clicking preview? If not, it may be having issues saving the preview version, though I'd expect details of that to get logged to the MODX log.
