### ISSUE TITLE
Doesn't work with Articles

### ISSUE THREAD

**Issue by pbowyer** [modmore/MagicPreview#26]
Preview is working great across the rest of the site, but on the one section that uses Articles, clicking the Preview button shows nothing. In the console there's the following JS error:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'formpanel')
    at MODx.Component.mpPreview (preview.js?v=1.2.3-pl:22:24)
    at S.onClick (ext-all.js:21:426947)
    at HTMLSpanElement.I (ext-all.js:21:57750)
```
which is
```js
            mpPreview: function() {
                var o = this.config;
                if (!o.formpanel) return false; <<< This line
```

#### Some insight
Normally `this` is an instance of `MODx.page.UpdateResource`, but on the Article resources it's an instance of `MODx.Component`.

#### Versions:
* Articles 1.8.0-pl
* Magic Preview 1.2.3-pl
* MODX 2.8.4-pl

**Comment by muzzwood** [comment]
Hi @pbowyer

From my initial testing it looks like this is only occurring on the articles themselves, rather than the Articles "Container". Does that line up with what you're seeing?

Could you try editing the preview.js file you referenced above, and replace lines 5-7:
```
        Ext.override(MODx.page.UpdateResource, {
            _originals: {
                getButtons: MODx.page.UpdateResource.prototype.getButtons
```

with the following:
```
        var basePage = MODx.page.UpdateResource;
        // Check if page is an "Article", if so extend that rather than the core one.
        if (typeof Articles !== 'undefined' && Articles.page.UpdateArticle) {
            basePage = Articles.page.UpdateArticle;
        }
        Ext.override(basePage, {
            _originals: {
                getButtons: basePage.prototype.getButtons
            },
```

If you can confirm that fixes the issue for you, I'll push a fix and get a new release out.
Cheers!

**Comment by pbowyer** [comment]
Hi @muzzwood,

Thanks, I can confirm that fixes it!

**Comment by muzzwood** [comment]
Thanks for reporting back, @pbowyer.
I'll get that into a new release this week. 🙂

**Comment by muzzwood** [comment]
Fixed in https://github.com/modmore/MagicPreview/commit/c84d1bd3dbb00f2dfeb0e1fe4216ad6f907cca67
