### ISSUE TITLE
Incorrect UI after button merge

### ISSUE THREAD

**Issue by ViperAix** [modmore/MagicPreview#33]
I have updated to 1.4.0-pl and since then something is wrong with my buttons.

The “View” button is in my Babel dropdown. But when I uninstall Babel, the letter “n” is still visible on the left side and I can trigger the click on the “View” button in both cases.

We use a customized manager theme, but the problem also occurs in the default theme. The browser cache has also already been cleared.

We have installed the latest MODX version 3.0.6-pl.

![image](https://github.com/user-attachments/assets/c8f7b5ac-2bd9-4b38-a2ac-3a93754c8b97)

![image](https://github.com/user-attachments/assets/e3bec82d-b7d4-435f-ba23-d3e32e518a36)

**Comment by muzzwood** [comment]
Hi @ViperAix ,

Hmmm that's an odd one. I just updated to 3.0.6 to see if I could reproduce it but no luck so far unfortunately.
![Screenshot 2024-12-13 at 18-20-20 Editing Home MODX Revolution](https://github.com/user-attachments/assets/0632ba27-1e0c-4c98-bfd0-340468534f16)

Can you try disabling all other plugins to see if something is conflicting? 
My other advice would be to switch back to the default theme, clear the cache, then do a browser hard refresh.. but it sounds like you've already tried that.

Are you getting any errors in the browser console?

**Comment by muzzwood** [comment]
Ah actually I just switched the manager language to German and I'm getting something similar. I think it's the `text-indent` CSS rule that's causing it. @jenswittmann what do you reckon?

**Comment by jenswittmann** [comment]
@ViperAix and @muzzwood i can reproduce it with the following setup:

- open resource that is a child of a collection (button "back to collection" appears)
- Babel Extra
- MagicPreview Extra

I think there is also a `overflow: auto;` needed. Can you test [this](https://github.com/modmore/MagicPreview/pull/34)?

**Comment by muzzwood** [comment]
Thanks for the quick response @jenswittmann ! 🎉 
That looks to work for me. What about you @ViperAix ?

**Comment by ViperAix** [comment]
> I think there is also a `overflow: auto;` needed. Can you test [this](https://github.com/modmore/MagicPreview/pull/34)?
This works for me :)

**Comment by muzzwood** [comment]
Fixed in #34

**Comment by muzzwood** [comment]
magicpreview-1.4.1-pl is now available. Thanks!
